default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_review_development
  username: Kamil
  password: Kamil

test:
  <<: *default
  database: book_review_test
  username: Kamil
  password: Kamil

production:
  <<: *default
  database: book_review_production
  username: Kamil
  password: Kamil
